// <auto-generated />
namespace Duiklogboek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Moved_Diver_model_into_ID_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moved_Diver_model_into_ID_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201605120921393_Moved_Diver_model_into_ID_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
